### ISSUE TITLE
undefined method `to_sym' for nil:NilClass

### ISSUE THREAD

**Issue by denys281** [scarfacedeb/rails_admin_globalize_field#10]
If in rails_admin.rb initializers I add translation for label, for example:

```
edit do
        field :title do
          label 'Назва'
        end
        field :description do
          label 'Опис'
        end
 end
```
After save I have error: 
```undefined method `to_sym' for nil:NilClass``` in 
```rails_admin_globalize_field (0.3.1) lib/rails_admin_globalize_field.rb```  line 48: ```new_locales = available_locales - translations.keys.map(&:to_sym)```

**Comment by scarfacedeb** [comment]
@denys281 @syzspectroom @travisvalentine 
I added spec to test this issue, but it passes in my environment.

Could you look at it, compare it with your own rails_admin configs and if it's possible try to make it fail?

**Comment by scarfacedeb** [comment]
I'm closing it due to inactivity. 

I can't resolve that issue without any example of faulty rails_admin config.

If anybody is still getting this error (with `field :locale, :hidden` line in model config), I'll be glad to take a look into it.

**Comment by gotjosh** [comment]
I have managed to re-create the problem.

When I use this syntax below, I do get the error

```ruby
field :locale do
  hide
end
```
However, when I use the suggested one of `field :locale, :hidden` I do not.

Perhaps this has something to with the implementation of `rails_admin`? Either I think that compact should ensure in order to fail silently.
